#
# Module manifest for module 'Better11'
#
# Generated by: Better11 Development Team
# Generated on: 12/10/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Better11.psm1'

    # Version number of this module.
    ModuleVersion = '0.3.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'a8f5c3e2-1d4b-4c9a-8e2f-3a6b5c7d8e9f'

    # Author of this module
    Author = 'Better11 Development Team'

    # Company or vendor of this module
    CompanyName = 'Better11'

    # Copyright statement for this module
    Copyright = '(c) 2025 Better11. MIT License.'

    # Description of the functionality provided by this module
    Description = 'PowerShell backend for Better11 Windows Enhancement Toolkit - Comprehensive Windows system management and optimization'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
        'Modules\AppManager\AppManager.psd1',
        'Modules\SystemTools\SystemTools.psd1',
        'Modules\Disk\Disk.psd1',
        'Modules\Network\Network.psd1',
        'Modules\Backup\Backup.psd1',
        'Modules\Power\Power.psd1',
        'Modules\Common\Common.psd1',
        'Modules\Safety\Safety.psd1',
        'Modules\Privacy\Privacy.psd1',
        'Modules\Updates\Updates.psd1',
        'Modules\Shell\Shell.psd1',
        'Modules\Gaming\Gaming.psd1',
        'Modules\SysInfo\SysInfo.psd1',
        'Modules\Features\Features.psd1',
        'Modules\Drivers\Drivers.psd1',
        'Modules\Tasks\Tasks.psd1',
        'Modules\Startup\Startup.psd1',
        'Modules\Performance\Performance.psd1'
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry,
    # use an empty array if there are no functions to export.
    FunctionsToExport = @(
        # AppManager
        'Get-Better11Apps',
        'Install-Better11App',
        'Uninstall-Better11App',
        'Update-Better11App',
        'Get-Better11AppStatus',
        'Get-Better11InstalledApps',
        
        # SystemTools
        'Get-Better11StartupItems',
        'Enable-Better11StartupItem',
        'Disable-Better11StartupItem',
        'Remove-Better11StartupItem',
        'Set-Better11RegistryTweak',
        'Remove-Better11Bloatware',
        'Set-Better11Service',
        'Get-Better11ServiceStatus',
        'Get-Better11RegistryValue',
        'Set-Better11RegistryValue',
        'Set-Better11ServiceStartMode',
        
        # Disk
        'Get-Better11DiskSpace',
        'Clear-Better11TempFiles',
        'Get-Better11DiskUsage',
        
        # Network
        'Get-Better11NetworkAdapters',
        'Set-Better11DNS',
        'Clear-Better11DNSCache',
        'Reset-Better11TcpIp',
        'Reset-Better11Winsock',
        'Test-Better11NetworkConnectivity',
        
        # Backup
        'Get-Better11RestorePoints',
        'New-Better11RestorePoint',
        'Backup-Better11Registry',
        'Backup-Better11RegistryHive',
        'Export-Better11Settings',
        'Import-Better11Settings',
        
        # Power
        'Get-Better11PowerPlans',
        'Set-Better11PowerPlan',
        'Enable-Better11Hibernation',
        'Disable-Better11Hibernation',
        'New-Better11BatteryReport',
        
        # Common
        'Write-Better11Log',
        'Test-Better11Administrator',
        'Confirm-Better11Action',
        'New-Better11Backup',
        
        # Safety
        'Backup-Better11RegistryKey',
        'Restore-Better11RegistryKey',
        
        # Privacy
        'Get-Better11TelemetryLevel',
        'Set-Better11TelemetryLevel',
        'Get-Better11AppPermission',
        'Set-Better11AppPermission',
        'Get-Better11AllPermissions',
        'Disable-Better11AdvertisingId',
        'Enable-Better11AdvertisingId',
        'Disable-Better11Cortana',
        'Enable-Better11Cortana',
        'Set-Better11PrivacyPreset',
        
        # Updates
        'Get-Better11AvailableUpdates',
        'Install-Better11Updates',
        'Suspend-Better11Updates',
        'Resume-Better11Updates',
        'Set-Better11ActiveHours',
        'Get-Better11ActiveHours',
        'Get-Better11UpdateHistory',
        'Uninstall-Better11Update',
        'Get-Better11UpdateSettings',
        
        # Shell
        'Get-Better11TaskbarSettings',
        'Set-Better11TaskbarAlignment',
        'Set-Better11SearchMode',
        'Set-Better11TaskViewVisible',
        'Set-Better11WidgetsVisible',
        'Set-Better11CopilotVisible',
        'Enable-Better11ClassicContextMenu',
        'Disable-Better11ClassicContextMenu',
        'Set-Better11ShellPreset',
        'Restart-Better11Explorer',
        
        # Gaming
        'Get-Better11GamingSettings',
        'Set-Better11GameMode',
        'Set-Better11GameBar',
        'Set-Better11GPUScheduling',
        'Set-Better11MouseAcceleration',
        'Disable-Better11NagleAlgorithm',
        'Enable-Better11NagleAlgorithm',
        'Set-Better11HighPerformancePower',
        'Set-Better11GamingPreset',
        
        # SysInfo
        'Get-Better11SystemSummary',
        'Get-Better11WindowsInfo',
        'Get-Better11CPUInfo',
        'Get-Better11MemoryInfo',
        'Get-Better11GPUInfo',
        'Get-Better11StorageInfo',
        'Get-Better11NetworkInfo',
        'Get-Better11BIOSInfo',
        'Export-Better11SystemInfo',
        
        # Features
        'Get-Better11OptionalFeatures',
        'Enable-Better11OptionalFeature',
        'Disable-Better11OptionalFeature',
        'Get-Better11InstalledCapabilities',
        'Add-Better11Capability',
        'Remove-Better11Capability',
        
        # Drivers
        'Get-Better11Drivers',
        'Get-Better11DriverIssues',
        'Backup-Better11Drivers',
        'Update-Better11Driver',
        'Export-Better11DriverList',
        
        # Tasks
        'Get-Better11ScheduledTasks',
        'Enable-Better11ScheduledTask',
        'Disable-Better11ScheduledTask',
        'Get-Better11TelemetryTasks',
        'Disable-Better11TelemetryTasks',
        'New-Better11ScheduledTask',
        'Remove-Better11ScheduledTask',
        
        # Startup
        'Get-Better11StartupPrograms',
        'Enable-Better11StartupProgram',
        'Disable-Better11StartupProgram',
        'Add-Better11StartupProgram',
        'Remove-Better11StartupProgram',
        'Get-Better11StartupImpact',
        
        # Performance
        'Get-Better11PerformanceSettings',
        'Set-Better11VisualEffects',
        'Set-Better11ProcessorScheduling',
        'Set-Better11VirtualMemory',
        'Enable-Better11FastStartup',
        'Disable-Better11FastStartup',
        'Set-Better11SystemResponsiveness',
        'Optimize-Better11Performance',
        'Get-Better11ResourceUsage'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry,
    # use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry,
    # use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    # This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Windows', 'Windows11', 'SystemManagement', 'Optimization', 
                     'Privacy', 'Backup', 'Network', 'PowerManagement', 'Better11')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/better11/better11/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/better11/better11'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
# Better11 PowerShell Module v0.3.0

## New Features
- Complete PowerShell backend implementation
- Application management cmdlets
- System optimization tools
- Disk and storage management
- Network configuration tools
- Backup and restore functionality
- Power management cmdlets
- Comprehensive logging and safety features

## Requirements
- Windows 11 (22H2 or later recommended)
- PowerShell 5.1+ or PowerShell 7+
- Administrator privileges for most operations

## Getting Started
```powershell
Import-Module Better11
Get-Better11Apps
Get-Better11DiskSpace
Get-Better11PowerPlans
```

For full documentation, visit: https://github.com/better11/better11
'@

            # Prerelease string of this module
            # Prerelease = 'beta'

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
